name: Force Sync Fork with Upstream 

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/xiaorouji/openwrt-passwall-packages.git
          git fetch upstream

      - name: Force reset to upstream/main
        run: |
          git checkout main
          git reset --hard upstream/main

      - name: Remove upstream workflows
        run: |
          rm -rf .github/workflows/*
      
      - name: Restore sync.yml
        run: |
          git checkout origin/main -- .github/workflows/sync.yml || echo "No sync.yml to restore"
          git add .github/workflows/sync.yml
          git commit -m "Restore sync.yml after sync" || echo "No changes to commit"

      - name: Push force to origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main --force
